import {
  Component,
  Input,
  Output,
  EventEmitter,
  ChangeDetectionStrategy,
  inject,
  computed,
  signal,
} from '@angular/core';
import { RouterLink } from '@angular/router';
import { DecimalPipe } from '@angular/common';
import { Product, ProductVariant } from '../../../core/services/product-mock.service';
import { AnalyticsService } from '../../../core/services/analytics.service';

/**
 * Presentational (dumb) card component that renders a single product.
 *
 * @description
 * Follows the **Smart / Dumb** component pattern:
 * - Receives all data via `@Input()`.
 * - Communicates user actions upward via `@Output()` EventEmitters.
 * - Contains zero business logic beyond computing the discount percentage.
 *
 * Accessibility:
 * - Each `<article>` is labelled by its `<h3>` via `aria-labelledby`.
 * - The rating widget uses a single `<p role="img">` so screen readers
 *   announce the accessible label instead of reading individual star characters.
 * - The CTA button has a descriptive `aria-label` that includes the product name.
 * - All interactive elements are reachable by keyboard in DOM order.
 *
 * Performance:
 * - `ChangeDetectionStrategy.OnPush` limits re-renders to reference changes.
 * - Product images use `loading="lazy"` (thumbnails) and standard `<img>`
 *   (SVG assets don't benefit from `srcset` generated by `NgOptimizedImage`).
 * - `view-transition-name` enables the native View Transitions API morph
 *   when navigating to the PDP.
 */
@Component({
  selector: 'app-product-card',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink, DecimalPipe],
  template: `
    <article
      class="product-card"
      [attr.aria-labelledby]="headingId"
    >
      <!-- ─── Image + badges ──────────────────────────────────────────── -->
      <a
        [routerLink]="['/producto', product.id]"
        class="product-card__image-link"
        (click)="onViewItem()"
        [attr.aria-label]="'Ver detalle de ' + product.name"
        tabindex="0"
      >
        <div class="product-card__image-wrapper">
          <img
            [src]="product.imageUrl"
            [alt]="product.name"
            width="280"
            height="280"
            loading="lazy"
            class="product-card__image product-image-transition"
            [style.view-transition-name]="'product-' + product.id"
          />

          @if (discountPercent > 0) {
            <span
              class="product-card__badge product-card__badge--discount"
              aria-label="Descuento del {{ discountPercent }} por ciento"
            >
              -{{ discountPercent }}%
            </span>
          }

          @if (product.prescription) {
            <span
              class="product-card__badge product-card__badge--rx"
              title="Requiere receta médica"
              aria-label="Requiere receta médica"
            >
              Rx
            </span>
          }
        </div>
      </a>

      <!-- ─── Product info ────────────────────────────────────────────── -->
      <div class="product-card__body">
        <p class="product-card__brand">{{ product.brand }}</p>

        <!-- h3: unique accessible name for this card, referenced by aria-labelledby -->
        <h3 class="product-card__name" [id]="headingId">
          <a
            [routerLink]="['/producto', product.id]"
            (click)="onViewItem()"
            [title]="product.name"
          >
            {{ product.name }}
          </a>
        </h3>

        <div class="product-card__interest">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg> 
          <span>Te puede interesar</span>
        </div>

        <div class="product-card__vendor">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><circle cx="12" cy="12" r="8" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="12" r="3"/></svg> 
          <span>Inkafarma</span>
        </div>

        <!-- Pricing as per Figma image -->
        <div class="product-card__prices-layout">
          <!-- Fila 1: Precio Regular -->
          <div class="product-card__price-row">
            <span class="product-card__price-label" [style.text-decoration]="currentVariant.originalPrice ? 'line-through' : 'none'">
              S/ {{ (currentVariant.originalPrice || currentVariant.price) | number:'1.2-2' }}
            </span>
          </div>

          <!-- Fila 2: Precio Promocional -->
          <div class="product-card__price-row">
            <span class="product-card__price-label" style="font-weight: 700; color: #1e293b;">
              S/ {{ currentVariant.price | number:'1.2-2' }}
            </span>
            <div class="product-card__price-right">
              @if (discountPercent > 0) {
                <span class="pc-price-tag pc-price-tag--dark">-{{ discountPercent }}%</span>
              }
            </div>
          </div>

          <!-- Fila 3: Precio Tarjeta -->
          <div class="product-card__price-row">
            <span class="product-card__price-label" style="font-weight: 700; color: #1e293b;">
              S/ {{ (currentVariant.price * 0.95) | number:'1.2-2' }}
            </span>
            <div class="product-card__price-right">
              <span class="product-card__card-icons">
                <span class="product-card__card-icon product-card__card-icon--black">
                  <svg viewBox="0 0 60 30" fill="none" width="24" height="12"><rect width="60" height="30" rx="8" fill="#000000"/><text x="10" y="22" font-family="Arial" font-weight="900" font-size="21" fill="#ffffff" letter-spacing="-0.5">síp</text><circle cx="47" cy="10" r="4.5" fill="#00B1FF"/></svg>
                </span>
                <span class="product-card__card-icon product-card__card-icon--blue">
                  <svg viewBox="0 0 60 30" fill="none" width="24" height="12"><rect width="60" height="30" rx="8" fill="#00B1FF"/><text x="10" y="22" font-family="Arial" font-weight="900" font-size="21" fill="#ffffff" letter-spacing="-0.5">sp</text><circle cx="47" cy="10" r="4.5" fill="#000000"/></svg>
                </span>
              </span>
              <span class="pc-price-tag pc-price-tag--blue">-{{ discountPercent > 0 ? discountPercent + 5 : 5 }}%</span>
            </div>
          </div>
        </div>

        <!-- CTA -->
        <div class="product-card__cta-group">
          <button
            class="product-card__cta btn btn--primary"
            [class.product-card__cta--success]="isAdded()"
            [id]="ctaId"
            (click)="onAddToCart()"
            [attr.aria-label]="'Agregar ' + product.name + ' al carrito'"
            type="button"
            [disabled]="isAdded()"
          >
            @if (isAdded()) {
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <polyline points="20 6 9 17 4 12"></polyline>
              </svg>
              Agregado
            } @else {
              Agregar al carrito
            }
          </button>
          
          <button class="product-card__btn-fav" aria-label="Agregar a favoritos" type="button">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z" />
            </svg>
          </button>
        </div>
      </div>
    </article>
  `,
  styles: [`
    .product-card {
      background: var(--color-bg-card);
      border-radius: var(--radius-card);
      box-shadow: var(--shadow-card);
      overflow: hidden;
      display: flex;
      flex-direction: column;
      height: 460px;
      max-height: 460px;
      transition:
        box-shadow 250ms cubic-bezier(0.4, 0, 0.2, 1),
        transform   250ms cubic-bezier(0.4, 0, 0.2, 1);

      &:hover {
        box-shadow: var(--shadow-card-hover);
        transform: translateY(-2px);
      }
    }

    .product-card__image-link {
      display: block;
      text-decoration: none;
    }

    .product-card__image-wrapper {
      position: relative;
      height: 150px;
      flex-shrink: 0;
      background: hsl(210, 16%, 96%);
      overflow: hidden;
    }

    .product-card__image {
      width: 100%;
      height: 100%;
      object-fit: contain;
      padding: 0.5rem;
      transition: transform 300ms ease;

      .product-card:hover & {
        transform: scale(1.04);
      }
    }

    .product-card__badge {
      position: absolute;
      top: 0.5rem;
      left: 0.5rem;
      padding: 0.2rem 0.5rem;
      border-radius: 9999px;
      font-size: 0.7rem;
      font-weight: 700;
      line-height: 1.4;
    }

    .product-card__badge--discount {
      background: var(--color-error);
      color: white;
    }

    .product-card__badge--rx {
      background: var(--color-brand-primary);
      color: white;
      top: auto;
      left: auto;
      right: 0.5rem;
      bottom: 0.5rem;
    }

    .product-card__body {
      padding: 1rem 1rem 1.25rem 1rem;
      display: flex;
      flex-direction: column;
      flex: 1;
      min-height: 0;
      overflow: hidden;
      gap: 0.25rem;
    }

    .product-card__brand {
      font-size: 0.7rem;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: var(--color-text-secondary);
    }

    .product-card__name {
      font-size: 0.875rem;
      font-weight: 600;
      line-height: 1.3;
      color: var(--color-text-primary);
      margin-bottom: 0.25rem;
      height: calc(0.875rem * 1.3 * 2);
      overflow: hidden;
      display: -webkit-box;
      -webkit-line-clamp: 2;
      -webkit-box-orient: vertical;

      a {
        color: inherit;
        text-decoration: none;
      }
      a:hover { color: var(--color-brand-primary); }
    }

    .product-card__interest {
      display: inline-flex;
      align-items: center;
      gap: 4px;
      background: #E8F4FF;
      color: #1A8FF1;
      padding: 4px 8px;
      border-radius: 9999px;
      font-size: 0.65rem;
      font-weight: 600;
      width: fit-content;
      margin-bottom: 0.5rem;
    }

    .product-card__vendor {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      color: #64748B;
      font-size: 0.75rem;
      font-weight: 500;
      margin-bottom: 1rem;
    }

    .product-card__prices-layout {
      display: flex;
      flex-direction: column;
      gap: 4px;
      margin-bottom: 1rem;
      margin-top: auto;
    }

    .product-card__price-row {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .product-card__price-label {
      font-size: 0.8rem;
      font-weight: 600;
      color: #64748B;
    }

    .product-card__price-right {
      display: flex;
      align-items: center;
      gap: 6px;
    }

    .product-card__card-icons {
      display: flex;
      gap: 2px;
    }

    .product-card__card-icon {
      border-radius: 2px;
      overflow: hidden;
      display: flex;
    }

    .pc-price-tag {
      font-size: 0.65rem;
      font-weight: 700;
      padding: 2px 4px;
      border-radius: 4px;
      color: white;
    }

    .pc-price-tag--dark {
      background: #354159;
    }

    .pc-price-tag--blue {
      background: #00B1FF;
    }

    .product-card__cta-group {
      display: flex;
      gap: 8px;
    }

    .product-card__btn-fav {
      width: 44px;
      height: 44px;
      border-radius: 200px;
      background: #EDF8F2;
      color: #17A15B;
      border: none;
      display: flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
      cursor: pointer;
      transition: transform 150ms ease, background 150ms ease;

      &:hover {
        background: #DDF1E6;
      }
      &:active {
        transform: scale(0.95);
      }
    }

    .product-card__cta {
      flex: 1;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 0 1rem;
      background: #17A15B;
      color: white;
      border-radius: 200px;
      font-size: 0.875rem;
      font-weight: 600;
      transition: background 200ms ease, transform 150ms ease;

      &:hover:not(:disabled) {
        background: #138C4F;
        transform: scale(1.02);
      }

      &:active:not(:disabled) { transform: scale(0.98); }
    }

    .product-card__cta--success {
      background: #10B981 !important;
      transform: scale(1.05);
      pointer-events: none;
    }
  `],
})
export class ProductCardComponent {
  /** The product to display. Required. */
  @Input({ required: true }) product!: Product;

  /**
   * The pre-selected variant whose price and label are shown.
   * Defaults to the first variant if not provided.
   */
  @Input() selectedVariant!: ProductVariant;

  /**
   * Emits when the user clicks "Agregar".
   * The parent is responsible for dispatching to `CartService`.
   */
  @Output() readonly addToCart = new EventEmitter<{
    readonly product: Product;
    readonly variant: ProductVariant;
  }>();

  private readonly _analytics = inject(AnalyticsService);

  /** Fixed star scale used to render the rating widget. */
  readonly starValues = [1, 2, 3, 4, 5] as const;
  
  /** Signal for the success animation state */
  readonly isAdded = signal(false);

  /** Stable ID connecting the article's `aria-labelledby` to the `<h3>`. */
  get headingId(): string {
    return `product-name-${this.product.id}`;
  }

  /** Stable ID for the "Agregar" button (unique per product on the page). */
  get ctaId(): string {
    return `add-to-cart-${this.product.id}`;
  }

  /**
   * Resolves the variant to display.
   * Uses `selectedVariant` if provided, otherwise falls back to the first variant.
   */
  get currentVariant(): ProductVariant {
    return this.selectedVariant ?? this.product.variants[0];
  }

  /**
   * Computes the discount percentage between `originalPrice` and `price`.
   *
   * @returns Integer percentage (e.g. `18`), or `0` when no discount applies.
   */
  get discountPercent(): number {
    const variant = this.currentVariant;
    if (!variant?.originalPrice) return 0;
    return Math.round(
      ((variant.originalPrice - variant.price) / variant.originalPrice) * 100,
    );
  }

  /** Emits an `addToCart` output event and tracks the GA4 eCommerce action. */
  onAddToCart(): void {
    if (this.isAdded()) return; // Previene doble click durante la animación
    
    const variant = this.currentVariant;
    this.addToCart.emit({ product: this.product, variant });
    this._analytics.trackAddToCart(
      this.product.id,
      this.product.name,
      variant.label,
      variant.price,
      1,
    );

    // Activar animación
    this.isAdded.set(true);
    setTimeout(() => {
      this.isAdded.set(false);
    }, 1500);
  }

  /** Tracks a GA4 `view_item` event when the user navigates to the PDP. */
  onViewItem(): void {
    const variant = this.currentVariant;
    this._analytics.trackViewItem(this.product.id, this.product.name, variant.price);
  }
}
