import {
  Component,
  Input,
  Output,
  EventEmitter,
  ChangeDetectionStrategy,
  inject,
  computed,
} from '@angular/core';
import { RouterLink } from '@angular/router';
import { DecimalPipe } from '@angular/common';
import { Product, ProductVariant } from '../../../core/services/product-mock.service';
import { AnalyticsService } from '../../../core/services/analytics.service';

/**
 * Presentational (dumb) card component that renders a single product.
 *
 * @description
 * Follows the **Smart / Dumb** component pattern:
 * - Receives all data via `@Input()`.
 * - Communicates user actions upward via `@Output()` EventEmitters.
 * - Contains zero business logic beyond computing the discount percentage.
 *
 * Accessibility:
 * - Each `<article>` is labelled by its `<h3>` via `aria-labelledby`.
 * - The rating widget uses a single `<p role="img">` so screen readers
 *   announce the accessible label instead of reading individual star characters.
 * - The CTA button has a descriptive `aria-label` that includes the product name.
 * - All interactive elements are reachable by keyboard in DOM order.
 *
 * Performance:
 * - `ChangeDetectionStrategy.OnPush` limits re-renders to reference changes.
 * - Product images use `loading="lazy"` (thumbnails) and standard `<img>`
 *   (SVG assets don't benefit from `srcset` generated by `NgOptimizedImage`).
 * - `view-transition-name` enables the native View Transitions API morph
 *   when navigating to the PDP.
 */
@Component({
  selector: 'app-product-card',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink, DecimalPipe],
  template: `
    <article
      class="product-card"
      [attr.aria-labelledby]="headingId"
    >
      <!-- ─── Image + badges ──────────────────────────────────────────── -->
      <a
        [routerLink]="['/producto', product.id]"
        class="product-card__image-link"
        (click)="onViewItem()"
        [attr.aria-label]="'Ver detalle de ' + product.name"
        tabindex="0"
      >
        <div class="product-card__image-wrapper">
          <img
            [src]="product.imageUrl"
            [alt]="product.name"
            width="280"
            height="280"
            loading="lazy"
            class="product-card__image product-image-transition"
            [style.view-transition-name]="'product-' + product.id"
          />

          @if (discountPercent > 0) {
            <span
              class="product-card__badge product-card__badge--discount"
              aria-label="Descuento del {{ discountPercent }} por ciento"
            >
              -{{ discountPercent }}%
            </span>
          }

          @if (product.prescription) {
            <span
              class="product-card__badge product-card__badge--rx"
              title="Requiere receta médica"
              aria-label="Requiere receta médica"
            >
              Rx
            </span>
          }
        </div>
      </a>

      <!-- ─── Product info ────────────────────────────────────────────── -->
      <div class="product-card__body">
        <p class="product-card__brand">{{ product.brand }}</p>

        <!-- h3: unique accessible name for this card, referenced by aria-labelledby -->
        <h3 class="product-card__name" [id]="headingId">
          <a
            [routerLink]="['/producto', product.id]"
            (click)="onViewItem()"
            [title]="product.name"
          >
            {{ product.name }}
          </a>
        </h3>

        <!--
          Rating: role='img' on a <p> lets screen readers announce the
          accessible label as a single unit rather than reading each star.
          Individual stars are aria-hidden to avoid noise.
        -->
        <p
          class="product-card__rating"
          role="img"
          [attr.aria-label]="product.rating + ' de 5 estrellas, ' + product.reviewCount + ' reseñas'"
        >
          @for (star of starValues; track star) {
            <span
              class="product-card__star"
              [class.product-card__star--filled]="star <= product.rating"
              aria-hidden="true"
            >★</span>
          }
          <span class="product-card__review-count" aria-hidden="true">
            ({{ product.reviewCount }})
          </span>
        </p>

        <!-- Pricing -->
        <div class="product-card__price-wrapper">
          @if (currentVariant.originalPrice) {
            <s class="product-card__price-old" aria-label="Precio anterior">
              PEN {{ currentVariant.originalPrice | number:'1.2-2' }}
            </s>
          }
          <p class="product-card__price" aria-label="Precio actual">
            PEN {{ currentVariant.price | number:'1.2-2' }}
          </p>
        </div>

        <!-- CTA -->
        <button
          class="product-card__cta btn btn--primary"
          [id]="ctaId"
          (click)="onAddToCart()"
          [attr.aria-label]="'Agregar ' + product.name + ' al carrito'"
          type="button"
        >
          <svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            aria-hidden="true"
            focusable="false"
          >
            <path d="M6 2L3 6v14a2 2 0 002 2h14a2 2 0 002-2V6l-3-4z"/>
            <line x1="3" y1="6" x2="21" y2="6"/>
            <path d="M16 10a4 4 0 01-8 0"/>
          </svg>
          Agregar
        </button>
      </div>
    </article>
  `,
  styles: [`
    .product-card {
      background: var(--color-bg-card);
      border-radius: var(--radius-card);
      box-shadow: var(--shadow-card);
      overflow: hidden;
      display: flex;
      flex-direction: column;
      height: 420px;
      max-height: 420px;
      transition:
        box-shadow 250ms cubic-bezier(0.4, 0, 0.2, 1),
        transform   250ms cubic-bezier(0.4, 0, 0.2, 1);

      &:hover {
        box-shadow: var(--shadow-card-hover);
        transform: translateY(-2px);
      }
    }

    .product-card__image-link {
      display: block;
      text-decoration: none;
    }

    .product-card__image-wrapper {
      position: relative;
      height: 180px;
      flex-shrink: 0;
      background: hsl(210, 16%, 96%);
      overflow: hidden;
    }

    .product-card__image {
      width: 100%;
      height: 100%;
      object-fit: contain;
      padding: 0.5rem;
      transition: transform 300ms ease;

      .product-card:hover & {
        transform: scale(1.04);
      }
    }

    .product-card__badge {
      position: absolute;
      top: 0.5rem;
      left: 0.5rem;
      padding: 0.2rem 0.5rem;
      border-radius: 9999px;
      font-size: 0.7rem;
      font-weight: 700;
      line-height: 1.4;
    }

    .product-card__badge--discount {
      background: var(--color-error);
      color: white;
    }

    .product-card__badge--rx {
      background: var(--color-brand-primary);
      color: white;
      top: auto;
      left: auto;
      right: 0.5rem;
      bottom: 0.5rem;
    }

    .product-card__body {
      padding: var(--spacing-card-padding);
      display: flex;
      flex-direction: column;
      flex: 1;
      min-height: 0;
      overflow: hidden;
      gap: 0.25rem;
    }

    .product-card__brand {
      font-size: 0.7rem;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: var(--color-text-secondary);
    }

    .product-card__name {
      font-size: 0.875rem;
      font-weight: 600;
      line-height: 1.3;
      color: var(--color-text-primary);
      margin-bottom: 0.25rem;
      height: calc(0.875rem * 1.3 * 2);
      overflow: hidden;
      display: -webkit-box;
      -webkit-line-clamp: 2;
      -webkit-box-orient: vertical;

      a {
        color: inherit;
        text-decoration: none;
      }
      a:hover { color: var(--color-brand-primary); }
    }

    /* Resets <p> default margin; role="img" semantics via attr */
    .product-card__rating {
      display: flex;
      align-items: center;
      gap: 1px;
      margin: 0 0 0.25rem;
    }

    .product-card__star {
      color: var(--color-border);
      font-size: 0.8rem;

      &--filled { color: hsl(45, 96%, 48%); }
    }

    .product-card__review-count {
      font-size: 0.7rem;
      color: var(--color-text-secondary);
      margin-left: 0.25rem;
    }

    .product-card__price-wrapper {
      margin-top: auto;
      margin-bottom: 0.75rem;
    }

    .product-card__price-old {
      font-size: 0.75rem;
      color: var(--color-text-price-old);
      display: block;
    }

    .product-card__price {
      font-size: 1.125rem;
      font-weight: 700;
      color: var(--color-text-price);
    }

    .product-card__cta {
      width: 100%;
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 0.5rem;
      padding: 0.6rem 1rem;
      background: var(--color-brand-accent);
      color: white;
      border-radius: var(--radius-button);
      font-size: 0.875rem;
      font-weight: 600;
      transition: background 200ms ease, transform 150ms ease;

      &:hover {
        background: var(--color-brand-accent-hover);
        transform: scale(1.02);
      }

      &:active { transform: scale(0.98); }

      /* Explicit focus-visible ring for keyboard users (WCAG 2.4.7) */
      &:focus-visible {
        outline: 2px solid var(--color-brand-accent);
        outline-offset: 2px;
      }
    }
  `],
})
export class ProductCardComponent {
  /** The product to display. Required. */
  @Input({ required: true }) product!: Product;

  /**
   * The pre-selected variant whose price and label are shown.
   * Defaults to the first variant if not provided.
   */
  @Input() selectedVariant!: ProductVariant;

  /**
   * Emits when the user clicks "Agregar".
   * The parent is responsible for dispatching to `CartService`.
   */
  @Output() readonly addToCart = new EventEmitter<{
    readonly product: Product;
    readonly variant: ProductVariant;
  }>();

  private readonly _analytics = inject(AnalyticsService);

  /** Fixed star scale used to render the rating widget. */
  readonly starValues = [1, 2, 3, 4, 5] as const;

  /** Stable ID connecting the article's `aria-labelledby` to the `<h3>`. */
  get headingId(): string {
    return `product-name-${this.product.id}`;
  }

  /** Stable ID for the "Agregar" button (unique per product on the page). */
  get ctaId(): string {
    return `add-to-cart-${this.product.id}`;
  }

  /**
   * Resolves the variant to display.
   * Uses `selectedVariant` if provided, otherwise falls back to the first variant.
   */
  get currentVariant(): ProductVariant {
    return this.selectedVariant ?? this.product.variants[0];
  }

  /**
   * Computes the discount percentage between `originalPrice` and `price`.
   *
   * @returns Integer percentage (e.g. `18`), or `0` when no discount applies.
   */
  get discountPercent(): number {
    const variant = this.currentVariant;
    if (!variant?.originalPrice) return 0;
    return Math.round(
      ((variant.originalPrice - variant.price) / variant.originalPrice) * 100,
    );
  }

  /** Emits an `addToCart` output event and tracks the GA4 eCommerce action. */
  onAddToCart(): void {
    const variant = this.currentVariant;
    this.addToCart.emit({ product: this.product, variant });
    this._analytics.trackAddToCart(
      this.product.id,
      this.product.name,
      variant.label,
      variant.price,
      1,
    );
  }

  /** Tracks a GA4 `view_item` event when the user navigates to the PDP. */
  onViewItem(): void {
    const variant = this.currentVariant;
    this._analytics.trackViewItem(this.product.id, this.product.name, variant.price);
  }
}
